title: BladeFuse
author: eckeman
email: naffe@apskitimun.nu
theme: jekyll-theme-hacker
description: > # this means to ignore newlines until "baseurl:"
  I have written an awesome description for my new site here!!

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage
