title: BladeFuse
author: eckeman
email: naffe@apskitimun.nu
theme: jekyll-theme-hacker
description: > # this means to ignore newlines until "baseurl:"
  This is THE most awesome site!!

# social links
username: eckeman # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage
